name: Sheldon CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  # Job 1: SAST - Static Code Analysis
  sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Semgrep
        if: always()
        run: |
          docker run --rm -v "${PWD}:/src" returntocorp/semgrep semgrep scan -o semgrep_report.json --json
      - name: Upload Semgrep output
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-report
          path: semgrep_report.json

      - name: Run Bandit
        if: always()
        run: |
          docker run --user $(id -u):$(id -g) --rm -v $(pwd):/src hysnsec/bandit -r /src -f json -o /src/bandit-output.json || true
      - name: Upload Bandit output
        uses: actions/upload-artifact@v3
        with:
          name: bandit-output
          path: bandit-output.json

      - name: Run Trufflehog
        if: always()
        run: |
          docker run --rm -v $(pwd):/src hysnsec/trufflehog filesystem /src --json | tee trufflehog-output.json
      - name: Upload Trufflehog output
        uses: actions/upload-artifact@v3
        with:
          name: trufflehog-output
          path: trufflehog-output.json

  # Job 2: Build and push Docker Image
  build:
    runs-on: ubuntu-latest
    needs: sast
    if: always()
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: monte710/sheldon:latest

      - name: Connecting to techriot.net 
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.CLOUD_HOST }}
          username: ${{ secrets.CLOUD_USERNAME }}
          password: ${{ secrets.CLOUD_PASSWORD }}
          script: |
            docker stop sheldon
            docker rm sheldon
            docker rmi monte710/sheldon
            docker pull monte710/sheldon
            docker run -itd -e SECRET_KEY="${{ secrets.SECRET_KEY }}" --name sheldon monte710/sheldon

  # Job 3: DAST - Dynammic Application Security Testing